version: "3"

services:
  postgres:
    build:
      context: ./data
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5431:80
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres

  api:
    hostname: cinevoraces_api
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 3005:3005
    restart: always
    volumes:
      - ./api:/api
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3005/movies", "||", "exit", "1"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 10
    #   start_period: 40s

  app:
    hostname: cinevoraces_app
    env_file:
      - .env
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # restart: always
    restart: on-failure
    volumes:
      - ./app:/app
    depends_on:
      - api
      # api :
      #   condition: service_healthy
    links:
      - api
  
  # nginx:
  #   depends_on:
  #     - app
  #     - api
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports: 
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx/conf/:/etc/nginx/conf.d/
  #     - ./certbot/www:/var/www/certbot/
  #     - ./certbot/conf/:/etc/nginx/ssl/

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/
  #     - ./certbot/conf/:/etc/letsencrypt/
