version: "3"

services:
  postgres:
    build:
      context: ./data
      dockerfile: Dockerfile.dev
    environment:
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    ports: 
      - 5432:5432
    restart: always
    
  api:
    environment:
      - POSTGRES_URL=postgres://${PG_USER}:${PG_PW}@postgres:5432/${PG_DB}
    depends_on:
      - postgres
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080 # API
      - 5555:5555 # Prisma Studio
    restart: always
    volumes:
      - ./api:/api

  app:
    depends_on:
      - api
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./app/:/app