version: "3"

services:

  postgres:
    build:
      context: ./data
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
      - ./data:/data
  
  api:
    env_file:
      - .env
    depends_on:
      - postgres
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3005:3005

  app:
    env_file: 
      - .env.app
    environment:
      - REACT_APP_API=http://localhost:3005
    depends_on:
      - api
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000

volumes:
  database:
    driver: local