services:
  app:
    env_file: 
      - .env.app
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app:/app

  api:
    env_file:
      - .env
    depends_on:
      - postgres
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./api:/api

  postgres:
    build:
      context: ./data
      dockerfile: Dockerfile
    environment:
      DB_PW: ${DB_PW}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
    restart: always
    volumes:
      - database:/var/lib/postgresql/data

  nginx:
    depends_on:
      - app
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 3050:80

volumes:
  database:
    driver: local