version: "3"

services:
  postgres:
    build:
      context: ./data
      dockerfile: Dockerfile.dev
    env_file:
      - .env.db
    ports:
      - 5432:5432
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    env_file:
      - .env.db
    depends_on:
      - postgres

  api:
    env_file:
      - .env.db
      - .env.api
    depends_on:
      - postgres
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080 # API
      - 5555:5555 # Prisma Studio
    restart: always
    volumes:
      - ./api:/api

  # app:
  #   depends_on:
  #     - api
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile.dev
  #   restart: always
  #   volumes:
  #     - ./app/:/app
