version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always
    volumes :
      - database:/var/lib/postgresql/data
      - ./data:/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5431:80
    env_file:
      - .env
    depends_on:
      - postgres

  api:
    container_name: api
    hostname: cinevoraces_api
    env_file:
      - .env
    depends_on:
      - postgres
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    restart: always
    volumes:
      - fastify_public:/api/public/

  app:
    container_name: app
    hostname: cinevoraces_app
    env_file:
      - .env
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - api

  nginx:
    container_name: nginx
    depends_on:
      - app
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports: 
      - 80:80

volumes:
  fastify_public:
  database: