version: "3"

services:
  app:
    env_file: 
      - .env.app
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    # volumes:
    #   - ./app:/app

  api:
    env_file:
      - .env
    depends_on:
      - postgres
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    # volumes:
    #   - ./api:/api

  postgres:
    build:
      context: ./data
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
      - ./data:/data

  nginx:
    depends_on:
      - app
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/:ro
      - .certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - .certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  database:
    driver: local