version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:16.1
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - database:/var/lib/postgresql/data

  api:
    container_name: api
    hostname: cinevoraces_api
    environment:
      - API_PORT=3005
      - ROOT_PATH=/api
      - JWT_SECRET=secret
      - COOKIE_SECRET=secret
    env_file:
      - .env
    depends_on:
      - postgres
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 3005:3005
      - 9229:9229
    restart: always
    volumes:
      - ./api:/api

  app:
    container_name: app
    hostname: cinevoraces_app
    environment:
      - API_BASE_URL_CSR=http://localhost:3005
      - API_BASE_URL_SSR=http://cinevoraces_api:3005
    env_file:
      - .env
    depends_on:
      - postgres
      - api
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./app:/app

volumes:
  database:
