services:
  app:
    env_file: 
      - .env
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    restart: always
    volumes:
      - ./app:/app
  nginx:
    depends_on:
      - app
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile