version: "3"

services:
  postgres:
    build:
      context: ./data
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5431:80
    env_file:
      - .env
    depends_on:
      - postgres

  api:
    hostname: cinevoraces_api
    env_file:
      - .env
    depends_on:
      - postgres
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 3005:3005
    restart: always
    volumes:
      - ./api:/api

  app:
    hostname: cinevoraces_app
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_BASE_URL_CSR=http://localhost:3005
    depends_on:
      - api
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./app:/app
