export { default as adminController } from './admin/controller';
export { default as authController } from './auth/controller';
export { default as episodesController } from './episodes/controller';
export { default as metricsController } from './metrics/controller';
export { default as moviesController } from './movies/controller';
export { default as publicController } from './public/controller';
export { default as reviewsController } from './reviews/controller';
export { default as seasonsController } from './seasons/controller';
export { default as usersController } from './users/controller';
