export enum env {
  COOKIE_SECRET,
  JWT_SECRET,
  PASS_REGEXP,
  POSTGRES_USER,
  POSTGRES_DB,
  POSTGRES_PASSWORD,
  POSTGRES_HOST,
  POSTGRES_PORT,
}

export const EEnvValues: env[] = [
  env.COOKIE_SECRET,
  env.JWT_SECRET,
  env.PASS_REGEXP,
  env.POSTGRES_USER,
  env.POSTGRES_DB,
  env.POSTGRES_PASSWORD,
  env.POSTGRES_HOST,
  env.POSTGRES_PORT,
];

export const EEnvKeys = {
  [env.COOKIE_SECRET]: 'COOKIE_SECRET',
  [env.JWT_SECRET]: 'JWT_SECRET',
  [env.PASS_REGEXP]: 'PASS_REGEXP',
  [env.POSTGRES_USER]: 'POSTGRES_USER',
  [env.POSTGRES_DB]: 'POSTGRES_DB',
  [env.POSTGRES_PASSWORD]: 'POSTGRES_PASSWORD',
  [env.POSTGRES_HOST]: 'POSTGRES_HOST',
  [env.POSTGRES_PORT]: 'POSTGRES_PORT',
};
