export enum Env {
  COOKIE_SECRET,
  JWT_SECRET,
  PASS_REGEXP,
  POSTGRES_USER,
  POSTGRES_DB,
  POSTGRES_PASSWORD,
  POSTGRES_HOST,
  POSTGRES_PORT,
  CLOUDINARY_URL,
  STORAGE_TEMP,
  STORAGE_POSTER,
  STORAGE_AVATAR
}

export const EEnvValues: Env[] = [
  Env.COOKIE_SECRET,
  Env.JWT_SECRET,
  Env.PASS_REGEXP,
  Env.POSTGRES_USER,
  Env.POSTGRES_DB,
  Env.POSTGRES_PASSWORD,
  Env.POSTGRES_HOST,
  Env.POSTGRES_PORT,
  Env.CLOUDINARY_URL,
  Env.STORAGE_TEMP,
  Env.STORAGE_POSTER,
  Env.STORAGE_AVATAR
];

export const EEnvKeys = {
  [Env.COOKIE_SECRET]: 'COOKIE_SECRET',
  [Env.JWT_SECRET]: 'JWT_SECRET',
  [Env.PASS_REGEXP]: 'PASS_REGEXP',
  [Env.POSTGRES_USER]: 'POSTGRES_USER',
  [Env.POSTGRES_DB]: 'POSTGRES_DB',
  [Env.POSTGRES_PASSWORD]: 'POSTGRES_PASSWORD',
  [Env.POSTGRES_HOST]: 'POSTGRES_HOST',
  [Env.POSTGRES_PORT]: 'POSTGRES_PORT',
  [Env.CLOUDINARY_URL]: 'CLOUDINARY_URL',
  [Env.STORAGE_TEMP]: 'STORAGE_TEMP',
  [Env.STORAGE_POSTER]: 'STORAGE_POSTER',
  [Env.STORAGE_AVATAR]: 'STORAGE_AVATAR'
};
