FROM node:18-slim

RUN apt-get update
RUN apt-get install -y openssl

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm i

COPY . .

RUN npx prisma generate

CMD ["npm", "run", "dev"]